# Site settings
title: Sebastien Pelletier
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
    Articles on Javascript, AngularJS, UI Design, HTML5 and CSS3
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sebpelletier.github.io" # the base hostname & protocol for your site
twitter_username: sebpelletier
github_username:  sebpelletier
permalink: /:year/:month/:title

sass:
    style: compressed

# Build settings
markdown: kramdown
